# Pytorch #
## Tensors ##

In [29]:
from __future__ import print_function
import torch

## Construct a 5x3 matrix

In [30]:
x = torch.empty(5,3)
print(x)

tensor(1.00000e-36 *
       [[ 0.0001,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.4158,  0.0000,  0.0000],
        [ 0.0000,  0.0001,  0.0000],
        [ 2.0183,  0.0000,  0.0000]])


## Construct a randomly initialized matrix ##

In [3]:
x = torch.rand(5,3)
print (x)

tensor([[ 0.2160,  0.9818,  0.4937],
        [ 0.8137,  0.0965,  0.5956],
        [ 0.1817,  0.9467,  0.7179],
        [ 0.4344,  0.3123,  0.5304],
        [ 0.9354,  0.5434,  0.4993]])


## Construct a Matrix filled with zedps pf type dtype long: ##

In [5]:
x = torch.zeros(5,3, dtype=torch.long)
print (x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


## Construct a tensor directly from data ##

In [6]:
x = torch.tensor([5.5,3])
print (x)

tensor([ 5.5000,  3.0000])


## Create a tensor basing on existing tensor. ##

In [9]:
x = x.new_ones(5,3, dtype= torch.double)
print (x)

x= torch.rand_like(x, dtype=torch.float) #takes the size of the previuos tensor 
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)
tensor([[ 0.8237,  0.9364,  0.7029],
        [ 0.4029,  0.0971,  0.6284],
        [ 0.2271,  0.5985,  0.2739],
        [ 0.8908,  0.3921,  0.6925],
        [ 0.8432,  0.7020,  0.2299]])


In [10]:
print(x.size())

torch.Size([5, 3])


## Operations ##
Addition

In [12]:
y = torch.rand(5,3)
print (x + y)
print(torch.add(x, y))

tensor([[ 1.3980,  1.4036,  1.2883],
        [ 1.1423,  0.5591,  0.6535],
        [ 0.7425,  0.6304,  1.0066],
        [ 1.5753,  1.0713,  0.7665],
        [ 0.9135,  1.4190,  0.2520]])
tensor([[ 1.3980,  1.4036,  1.2883],
        [ 1.1423,  0.5591,  0.6535],
        [ 0.7425,  0.6304,  1.0066],
        [ 1.5753,  1.0713,  0.7665],
        [ 0.9135,  1.4190,  0.2520]])


Addition in place

In [16]:
print(x)
y.add_(x)
print(y)

tensor([[ 0.8237,  0.9364,  0.7029],
        [ 0.4029,  0.0971,  0.6284],
        [ 0.2271,  0.5985,  0.2739],
        [ 0.8908,  0.3921,  0.6925],
        [ 0.8432,  0.7020,  0.2299]])
tensor([[ 3.8690,  4.2129,  3.3969],
        [ 2.3509,  0.8504,  2.5388],
        [ 1.4239,  2.4258,  1.8283],
        [ 4.2477,  2.2475,  2.8440],
        [ 3.4432,  3.5251,  0.9417]])


You can use Numpy like indexing 

In [18]:
print(x[:,1])

tensor([ 0.9364,  0.0971,  0.5985,  0.3921,  0.7020])


Resizing tensors

In [21]:
x = torch.randn(4,4)
y = x.view(16)
z= x.view(-1,8) # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
print (x.size(),y.size(),z.size())

tensor([[ 1.6787,  0.3622, -0.7174, -1.4772],
        [-0.4052, -0.3431, -0.8034, -1.2759],
        [-0.1397, -1.4649,  1.2471, -0.7167],
        [ 0.2038, -0.1035,  0.9155, -1.5032]])
tensor([ 1.6787,  0.3622, -0.7174, -1.4772, -0.4052, -0.3431, -0.8034,
        -1.2759, -0.1397, -1.4649,  1.2471, -0.7167,  0.2038, -0.1035,
         0.9155, -1.5032])
tensor([[ 1.6787,  0.3622, -0.7174, -1.4772, -0.4052, -0.3431, -0.8034,
         -1.2759],
        [-0.1397, -1.4649,  1.2471, -0.7167,  0.2038, -0.1035,  0.9155,
         -1.5032]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use .item() to get the value as a Python number

In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6234])
-0.6234117150306702


Converting a Torch Tensor to a NumPy Array

In [24]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[ 1.  1.  1.  1.  1.]


In [25]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


Converting NumPy Array to Torch Tensor

In [28]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[ 1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
